cuzco/urls.py
from django.urls import path, include
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('weather/', include('weather.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls', namespace='auth')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    ]

weather/urls.py
from django.urls import path

from . import views
from .models import RequestArchive

app_name = 'weather'

urlpatterns = [
    # ex: /weather/
    path('', views.CitiesView.as_view(), name='cities'),
    # # ex: /weather/uname
    # url(r'^u(?P<username>\w+)/$', views.CitiesView.as_view(), name='cities'),

    # ex: /weather/2/
    path('<int:pk>/', views.CityView.as_view(), name='city_view'),
    # ex: /weather/upd/2/
    path('upd/<int:city_id>/', views.city_update, name='city_update'),
    
    # ex: /weather/(owm|yahoo)fc/6/
    path('owmfc/<int:pk>/', views.OWMView.as_view(), name='owm_view'),
    path('yahoofc/<int:pk>/', views.YahooView.as_view(), name='yahoo_view'),

    # ex: /weather/cron?username=<>&password=<>
    path('cron/', views.cron, name='cron'),

    # ex: /weather/archive/
    path('archive/',
        views.RequestTodayArchiveView.as_view(model=RequestArchive, date_field="req_date"),
        name="archive"),
    # ex: /weather/archive/1970/1/1/
    path('archive/<int:year>/<int:month>/<int:day>/',
        views.RequestDayArchiveView.as_view(month_format='%m'),
        name="archive_day"),
    ]

weather/models.py
from django.db import models

# Create your models here.
import datetime
from django.utils import timezone

class City(models.Model):
    name = models.CharField(max_length=100)
    ds_owm = models.URLField()
    ds_yahoo = models.URLField(max_length=250)
    turn = models.BooleanField(default=True)
    user_name = models.CharField(max_length=100)
    
    def __str__(self):
        return '{} {}'.format(self.name, self.turn)

class OWM(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    req_date = models.DateTimeField('request date')
    iden = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    coord_lon = models.CharField(max_length=100)
    coord_lat = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    population = models.CharField(max_length=100)
    sys_population = models.CharField(max_length=100)
    cod = models.CharField(max_length=100)
    message = models.CharField(max_length=100)
    cnt = models.CharField(max_length=100)

    def __str__(self):
        return '{}{:_>10}{:_>10}{:_>10}{:_>10}'.format(str(self.req_date), self.cod, self.message, self.cnt, self.name)

    def was_requested_recently(self):
        return self.req_date >= timezone.now() - datetime.timedelta(days=1)

class OWMForecast(models.Model):
    owm = models.ForeignKey(OWM, on_delete=models.CASCADE)
    forecast_text = models.CharField(max_length=1200)

    def __str__(self):
        return self.forecast_text

class Yahoo(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    req_date = models.DateTimeField('request date')
    name = models.CharField(max_length=100)
    coord_lon = models.CharField(max_length=100)
    coord_lat = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    yql_resp_text = models.CharField(max_length=3500)

    def __str__(self):
        return '{}{:_>10}'.format(str(self.req_date), self.name)

    def was_requested_recently(self):
        return self.req_date >= timezone.now() - datetime.timedelta(days=1)

class YahooForecast(models.Model):
    yahoo = models.ForeignKey(Yahoo, on_delete=models.CASCADE)
    forecast_text = models.CharField(max_length=1200)

    def __str__(self):
        return self.forecast_text


class RequestArchive(models.Model):
    id = models.BigIntegerField(primary_key=True)
    #city = models.ForeignKey(City, on_delete=modeles.DO_NOTHING)
    req_date = models.DateTimeField('request date')
    name = models.CharField(max_length=100)
    tn = models.CharField(max_length=100)
    cod = models.CharField(max_length=100)
    message = models.CharField(max_length=100)
    cnt = models.CharField(max_length=100)
    
    class Meta:
        managed = False
        db_table = 'weather_req_arc'

weather/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.contrib.auth import authenticate, login, logout
import requests
import json
from django.utils import timezone
from django.views import generic
import ephem
import datetime
import pytz
from bokeh.plotting import figure
from bokeh.models import Range1d, LinearAxis
import numpy as np
from bokeh.embed import components
from django.contrib.auth.decorators import login_required
from django.views.generic.dates import TodayArchiveView, DayArchiveView
from dateutil import parser
import time


from .models import City, OWM, OWMForecast, Yahoo, YahooForecast, RequestArchive
from .sbcalendar import SideBarCalendar

# Create your views here.
def cron(request):
    username = request.GET['username']
    password = request.GET['password']
    user = authenticate(username=username, password=password)

    context = dict()
    
    if user is None:
        context.update({
            'fail': '',
            'error': 'auth fail'
        })
        
        return render(request, 'weather/cron.html', context)

    login(request, user)

    c = City.objects.filter(turn=True).first()
    if c is None:
        City.objects.all().update(turn=True)
        c = City.objects.first()

    c.turn = False
    c.save()

    context.update({'city': {'name': c.name, 'ds_owm': c.ds_owm, 'ds_yahoo': c.ds_yahoo}})

    get_owm(request, context, c)
    get_yahoo(request, context, c)
    
    logout(request)
        
    return render(request, 'weather/cron.html', context)

def get_owm(request, context, c):
    resp = requests.get(c.ds_owm)
    for i in [1]:#,2,3,5]:
        if resp is None:
            time.sleep(1)
            context.update(
                {'owm': {
                    'fail': '',
                    'error': c.ds_owm + ': no response'
            }})
            continue

        pj = json.loads(resp.text)
        resp.close()
        
        if pj['cod'] != '200':
            time.sleep(1)
            context.update(
                {'owm': {
                    'fail': '',
                    'error': pj['cod'] + ', ' + pj['message']
                }})
            continue

        break
        
    else:
        owm = OWM()
        owm.message = context['owm']['error']
        owm.city = c
        owm.req_date = timezone.now()
        owm.save()
        logout(request)
        return
        
    context.update(
        {'owm': {
            'ok': '' #cron-job.org: Response data too big#resp.text #TODO:pretty print json.dumps(pj, sort_keys=True, indent=4),
        }})

    owm = OWM()

    owm.iden = pj['city']['id']
    owm.name = pj['city']['name']
    owm.coord_lon = pj['city']['coord']['lon']
    owm.coord_lat = pj['city']['coord']['lat']
    owm.country = pj['city']['country']
    #owm.population = pj['city']['population']
    #owm.sys_population = pj['city']['sys']['population']

    owm.cod = pj['cod']
    owm.message = pj['message']
    owm.cnt = pj['cnt']

    owm.city = c
    owm.req_date = timezone.now()

    owm.save()

    for fcs in pj['list']:
        owm_forecast = OWMForecast()

        owm_forecast.owm = owm
        owm_forecast.forecast_text = fcs
        owm_forecast.save()

    return

def get_yahoo(request, context, c):
    resp = requests.get(c.ds_yahoo)

    if resp is None:
        context.update(
            {'yahoo': {
                'fail': '',
                'error': c.name + ' req fail'
                }})
        yah = Yahoo()
        yah.yql_resp_text = c.ds_yahoo + ': no response'
        yah.city = c
        yah.req_date = timezone.now()
        yah.save()
        
        return

    pj = json.loads(resp.text)

    if pj['query']['count'] == 0:
        context.update(
            {'yahoo': {
                'fail': '',
                'error': c.name + ': results are None'
                }})
        yah = Yahoo()
        yah.yql_resp_text = c.ds_yahoo + ': no results'
        yah.city = c
        yah.req_date = timezone.now()
        yah.save()
        
        return

    context.update(
        {'yahoo': {
            'ok': '' #cron-job.org: Response data too big#resp.text #TODO:pretty print json.dumps(pj, sort_keys=True, indent=4),
        }})
    yah = Yahoo()
    yah.name = pj['query']['results']['channel']['location']['city']
    yah.coord_lat = pj['query']['results']['channel']['item']['lat']
    yah.coord_lon = pj['query']['results']['channel']['item']['long']
    yah.country = pj['query']['results']['channel']['location']['country']
    yah.region = pj['query']['results']['channel']['location']['region']
    yah.yql_resp_text = resp.text
    resp.close()
    yah.city = c
    yah.req_date = timezone.now()
    yah.save()

    for fcs in pj['query']['results']['channel']['item']['forecast']:
        yah_forecast = YahooForecast()

        yah_forecast.yahoo = yah
        yah_forecast.forecast_text = fcs
        yah_forecast.save()

    return
    
class CitiesView(generic.ListView): #(LoginRequiredMixin, generic.ListView):
    #login_url = ''
    #redirect_field_name = ''
    template_name = 'weather/city_list.html'
    context_object_name = 'city_list' #== object_list
    paginate_by = 20

    def get_queryset(self):
        city_list = list()
        if 'username' in self.kwargs and \
           self.kwargs['username'] == self.request.user.username:

            username = self.request.user.username
            cities = get_list_or_404(City, user_name=username)
        else:
            cities = get_list_or_404(City)

        for c in sorted(cities, key=lambda x: x.name):
            owmd = draw_owm(c)
            yahd = draw_yah(c)
            city_list.append({'city': c,
                              'owm': {'owm': owmd['o'],
                                      'sunrise':owmd['sr'], 'sunset': owmd['st'],
                                      'forecasts': owmd['fcs'][:9],
                                      'script': owmd['script'], 'div': owmd['div']},
                              'yahoo': {'yahoo': yahd['y'], 'yah':yahd['yy'],
                                        'forecasts': yahd['fcs'][:9],
                                        'script': yahd['script'], 'div': yahd['div']}})

        #import pdb; pdb.set_trace()
        return city_list
    
def draw_owm(c):
    o = c.owm_set.latest('req_date')
    
    sr, st = calc_ss(
        d=o.req_date.day, m=o.req_date.month, y=o.req_date.year, h=o.req_date.hour,
        lat=o.coord_lat, lon=o.coord_lon)

    sr = timezone.localtime(timezone.make_aware(sr.datetime()), timezone=pytz.timezone('Europe/Moscow'))
    st = timezone.localtime(timezone.make_aware(st.datetime()), timezone=pytz.timezone('Europe/Moscow'))

    fcs = []
    tempd = []
    tempnd = []
    tempxd = []
    windd = []
    presd = []
    pressd = []
    presgd = []
    humid = []
    precd = []
    timed = []
    for f in o.owmforecast_set.order_by('id'):
        fd = json.loads(f.forecast_text.replace("'",'"'))

        tempd.append(float(fd['main']['temp']) - 273.15)
        fd['main']['temp'] = "{0:.1f}".format(tempd[-1])
        tempnd.append(float(fd['main']['temp_min']) - 273.15)
        fd['main']['temp_min'] = "{0:.1f}".format(tempnd[-1])
        tempxd.append(float(fd['main']['temp_max']) - 273.15)
        fd['main']['temp_max'] = "{0:.1f}".format(tempxd[-1])

        windd.append(float(fd['wind']['speed']))
        presd.append(float(fd['main']['pressure']))
        pressd.append(float(fd['main']['sea_level']))
        presgd.append(float(fd['main']['grnd_level']))
        humid.append(float(fd['main']['humidity']))

        if 'snow' in fd and '3h' in fd['snow']:
            precd.append(float(fd['snow']['3h']))
        elif 'rain' in fd and '3h' in fd['rain']:
            precd.append(float(fd['rain']['3h']))
        else:
            precd.append(0)

        fd['dt'] = datetime.datetime.fromtimestamp(int(fd['dt']), pytz.timezone('UTC'))
        #import pdb; pdb.set_trace()
        fd['dt'] = fd['dt'].astimezone(pytz.timezone('Europe/Moscow'))
        #import pdb; pdb.set_trace()
        timed.append(fd['dt'])

        fcs.append(fd)

    script, div = {}, {}

    p = figure(
        width=600, height=230, 
        tools="",
        toolbar_location=None,
        title='Weather and forecasts in {}, {}'.format(o.name, o.country),
        x_axis_type="datetime",
        x_axis_label='', y_axis_label=''
        )
    p.sizing_mode = 'scale_width'
    p.extra_y_ranges = {"prec": Range1d(start=0, end=max([0]+precd))}
    p.add_layout(LinearAxis(y_range_name="prec"), 'right')
    x=np.append(timed, timed[::-1])
    y=np.append(tempnd, tempxd[::-1])
    p.patch(x, y, color='#7570B3', fill_alpha=0.2)
    p.vbar(x=timed, width=5000000, top=precd, legend="Precipitation, mm", color="grey", y_range_name="prec")
    p.line(timed, tempd, legend="Temperature, °C", line_width=3, color='blue')

    script['temp'], div['temp'] = components(p)

    p = figure(
        width=600, height=230, 
        tools="",
        toolbar_location=None,
        title='Weather and forecasts in {}, {}'.format(o.name, o.country),
        x_axis_type="datetime",
        x_axis_label='', y_axis_label=''
        )
    p.sizing_mode = 'scale_width'
    us='#fff5e6 #ffebcc #ffe0b3 #ffd699 #ffcc80 #ffc266 #ffb84d ' +\
       '#ffad33 #ffa31a #ff9900 #e68a00 #cc7a00 #b36b00 #995c00 ' +\
       '#804d00 #663d00 #4d2e00 #331f00 #1a0f00'
    ls='#f0f5f5 #e0ebeb #d1e0e0 #c2d6d6 #b3cccc #a3c2c2 #94b8b8 ' +\
       '#85adad #75a3a3 #669999 #5c8a8a #527a7a #476b6b #3d5c5c ' +\
       '#334d4d #293d3d #1f2e2e #141f1f #0a0f0f'
    us = us.split()
    us = us[:5]
    us = us[::-1]
    ls = ls.split()
    ls = ls[:5]
    x = np.append(timed, timed[::-1])
    unp=70
    lnp=40
    up=100
    lp=0
    y = [lp + i * (lnp - lp) / len(ls) for i in range(0, len(ls) + 1)] +\
        [unp + i * (up - unp) / len(us) for i in range(0, len(us) + 1)]
    i = 0
    #import pdb; pdb.set_trace()

weather/templates/weather/city_detail.html
{% extends 'base.html' %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block content %}

<div class="page-header">
  <h3>{{ city.name }}
    <a href="{% url 'weather:city_update' city.id %}">
      <i class="fa fa-edit"></i>
    </a>
  </h3>
</div>

<div class="row">
  <div class="col-md-12">
    {% if page_obj %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Req Date</th>
          <th>Req Info</th>
          <th>Iden</th>
          <th>Name</th>
          <th>Coord</th>
        </tr>
      </thead>
      <tbody>
	{% for owm in owm_list %}
	<tr>
	  <td><a href="{% url 'weather:owm_view' owm.id %}">{{ owm.req_date }}</a></td>
	  <td>{{ owm.cod }}, {{ owm.message }}, {{ owm.cnt }}</td>
	  <td>{{ owm.iden }}</td>
	  <td>{{ owm.name }}</td>
	  <td>{{ owm.coord_lon }}, {{ owm.coord_lat }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>No reqs are available.</p>
    {% endif %}
  </div>
</div>
<p>
  {% if page_obj.has_previous %}
  <a href="?page=1">first</a>
  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
  {% endif %}

  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">next</a>
  <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
  {% endif %}
</p>
{% endblock %}

{% block footer %}
{{ request.user.username }}
{% endblock %}

weather/templates/weather/cron.html
{% if fail == '' %}
<h3>{{ error }}</h3>
{% elif owm.fail == '' %}
<h3>{{ owm.error }}</h3>
<h3>{{ city.name }}</h3>
<h5>{{ city.ds_owm }}</h5>
{% elif yahoo.fail == '' %}
<h3>{{ yahoo.error}}</h3>
<h3>{{ city.name }}</h3>
<h5>{{ city.ds_yahoo }}</h5>
{% else %}
<h3>ok</h3>
<h3>{{ city.name }}</h3>
<h5>{{ city.ds_owm }}</h5>
{{ owm.ok }}
<h5>{{ city.ds_yahoo }}</h5>
{{ yahoo.ok }}
{% endif %}

weather/templates/weather/owm_detail.html
{% load static %}
{% static 'weather/icons/w' as icons %}
{% load tz %}
{% localtime off %}
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <div class="well">{{ owm.name }} {{ owm.req_date|date:"r" }}</div>
</div>
<div class="modal-body">
  <table class="table table-striped table-bordered small">
    {% for f in owmforecast_list %}
    <tr>
      <td><b>{{ f.date|date:"D" }}</b> {{ f.date|date:"m/d H:i" }}
          <img src="{{ icons }}/{{ f.weather.0.icon }}.png"></td>
      <td>{{ f.main.temp_max }} / {{ f.main.temp_min }} °C</td>
      <td>{{ f.main.pressure }} hpa</td>
      <td>{{ f.main.humidity}}%</td>
      <td>{{ f.wind.speed }} m/s</td>
      <td>{{ f.weather.0.description }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
{% endlocaltime %}

weather/templates/weather/requestarchive_archive_day.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-7">
    {% if city_day_conds %}
    {% for c in city_day_conds %}
    <div class="card">
      <div class="card-header">{{ c.city.name }}</div>
      <div class="card-body">
	<ul class="nav nav-tabs" role="tablist">
	  <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#owm{{ c.city.id }}">Open Weather Map</a></li>
	  <li class="nav-item">
            <a class="nav-link       " data-toggle="tab" href="#yah{{ c.city.id }}">Yahoo</a></li>
	</ul>

	<div class="tab-content">
	  
	  <div id="owm{{ c.city.id }}" class="tab-pane active container"><br>
	    <ul class="nav nav-tabs" role="tablist">
	      <li class="nav-item">
		<a  class="nav-link active" data-toggle="tab" href="#owmtemp{{ c.city.id }}">Temperature</a></li>
	      <li class="nav-item">
		<a  class="nav-link       " data-toggle="tab" href="#owmwind{{ c.city.id }}">Wind</a></li>
	      <li class="nav-item">
		<a  class="nav-link       " data-toggle="tab" href="#owmpres{{ c.city.id }}">Pressure</a></li>
	      <li class="nav-item">
		<a  class="nav-link       " data-toggle="tab" href="#owmhumi{{ c.city.id }}">Humidity</a></li>
	    </ul>

	    <div class="tab-content">
	      
	      <div id="owmtemp{{ c.city.id }}" class="tab-pane active container">
		  {{ c.owm.script.temp|safe }}
		  {{ c.owm.div.temp|safe }}
	      </div>
	      <div id="owmwind{{ c.city.id }}" class="tab-pane fade container">
	          {{ c.owm.script.wind|safe }}
		  {{ c.owm.div.wind|safe }}
	      </div>
	      <div id="owmpres{{ c.city.id }}" class="tab-pane fade container">
		  {{ c.owm.script.pres|safe }}
		  {{ c.owm.div.pres|safe }}
	      </div>
	      <div id="owmhumi{{ c.city.id }}" class="tab-pane fade container">
		  {{ c.owm.script.humi|safe }}
		  {{ c.owm.div.humi|safe }}
	      </div>
	    </div>
	  </div>

	  <div id="yah{{ c.city.id }}" class="tab-pane fade container"><br>
	    <ul class="nav nav-tabs" role="tablist">
	      <li class="nav-item">
		<a  class="nav-link active" data-toggle="tab" href="#yahtemp{{ c.city.id }}">Temperature</a></li>
	      <li class="nav-item">
		<a  class="nav-link       " data-toggle="tab" href="#yahwind{{ c.city.id }}">Wind</a></li>
	      <li class="nav-item">
		<a  class="nav-link       " data-toggle="tab" href="#yahpres{{ c.city.id }}">Pressure</a></li>
	      <li class="nav-item">
		<a  class="nav-link       " data-toggle="tab" href="#yahhumi{{ c.city.id }}">Humidity</a></li>
	    </ul>

	    <div class="tab-content">
	      
	      <div id="yahtemp{{ c.city.id }}" class="tab-pane active container">
		  {{ c.yahoo.script.temp|safe }}
		  {{ c.yahoo.div.temp|safe }}
	      </div>
	      <div id="yahwind{{ c.city.id }}" class="tab-pane fade container">
	          {{ c.yahoo.script.wind|safe }}
		  {{ c.yahoo.div.wind|safe }}
	      </div>
	      <div id="yahpres{{ c.city.id }}" class="tab-pane fade container">
		  {{ c.yahoo.script.pres|safe }}
		  {{ c.yahoo.div.pres|safe }}
	      </div>
	      <div id="yahhumi{{ c.city.id }}" class="tab-pane fade container">
		  {{ c.yahoo.script.humi|safe }}
		  {{ c.yahoo.div.humi|safe }}
	      </div>
	    </div>
	  </div>
	  
	</div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No cities are available.</p>
    {% endif %}
  </div>
  <div class="col-md-5">
    {% autoescape off %}
    {{ calendar }}
    {% endautoescape %}
    {% if page_obj %}
    <table class="table table-striped">
      {% comment %}
      <thead>
	<tr>
          <th>Req Date</th>
          <th>Req Info</th>
          <th>Name</th>
          <th>Data Source</th>
	</tr>
      </thead>
      {% endcomment %}
      <tbody>
	{% for ds in object_list %}
	<tr>
	  {% if ds.tn == 'owm' %}
          <td><a href="{% url 'weather:owm_view' ds.id %}" data-toggle="modal" data-target="#owmModal{{ ds.id }}">
              {{ ds.req_date|date:"H:i" }}</a></td>
          <div class="modal fade" id="owmModal{{ ds.id }}" role="dialog">
            <div class="modal-dialog modal-lg">
              <div class="modal-content"></div></div></div>
          {% elif ds.tn == 'yahoo' %}
          <td><a href="{% url 'weather:yahoo_view' ds.id %}" data-toggle="modal" data-target="#yahModal{{ ds.id }}">
              {{ ds.req_date|date:"H:i" }}</a></td>
          <div class="modal fade" id="yahModal{{ ds.id }}" role="dialog">
            <div class="modal-dialog modal-lg">
              <div class="modal-content"></div></div></div>
	  {% endif %}
	  <td>{{ ds.name }}</td>
	  <td>{{ ds.tn }}</td>
	  <td>{{ ds.cod }}, {{ ds.message }}, {{ ds.cnt }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>No reqs are available.</p>
    {% endif %}
    <p>
      {% if page_obj.has_previous %}
      <a href="?page=1">first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
      {% endif %}
    </p>
    <p>
      {% if previous_day %}
      Previous Day: <a href="{% url 'weather:archive_day' previous_day.year previous_day.month previous_day.day %}">
	{{ previous_day }}</a>
      {% endif %}
      {% if previous_day and next_day %}--{% endif %}
      {% if next_day %}
      Next Day: <a href="{% url 'weather:archive_day' next_day.year next_day.month next_day.day %}">
	{{ next_day }}</a>
      {% endif %}
    </p>
  </div>
</div>
{% endblock %}

{% block footer %}
{{ request.user.username }}
{% endblock %}

weather/templates/weather/yahoo_detail.html
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <div class="well">{{ yahoo.name }} {{ yahoo.req_date }}</div>
    </div>
    <div class="modal-body">
      <table class="table table-striped table-bordered small">
	{% for f in yahooforecast_list %}
	<tr>
	  <td><b>{{ f.day }}</b> {{ f.date|date:"m/d" }}</td>
	  <td><img src="http://l.yimg.com/a/i/us/we/52/{{ f.code }}.gif"></td>
	  <td>{{ f.high }} / {{ f.low }} °C</td>
	  <td>{{ f.text }}</td>
	</tr>
	{% endfor %}
      </table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>