cuzco/urls.py
from django.urls import path, include
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('weather/', include('weather.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls', namespace='auth')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    ]

weather/urls.py
from django.urls import path

from . import views
from .models import RequestArchive

app_name = 'weather'

urlpatterns = [
    # ex: /weather/
    path('', views.CitiesView.as_view(), name='cities'),
    # # ex: /weather/uname
    # url(r'^u(?P<username>\w+)/$', views.CitiesView.as_view(), name='cities'),

    # ex: /weather/2/
    path('<int:pk>/', views.CityView.as_view(), name='city_view'),
    # ex: /weather/upd/2/
    path('upd/<int:city_id>/', views.city_update, name='city_update'),
    
    # ex: /weather/(owm|yahoo)fc/6/
    path('owmfc/<int:pk>/', views.OWMView.as_view(), name='owm_view'),
    path('yahoofc/<int:pk>/', views.YahooView.as_view(), name='yahoo_view'),

    # ex: /weather/cron?username=<>&password=<>
    path('cron/', views.cron, name='cron'),

    # ex: /weather/archive/
    path('archive/',
        views.RequestTodayArchiveView.as_view(model=RequestArchive, date_field="req_date"),
        name="archive"),
    # ex: /weather/archive/1970/1/1/
    path('archive/<int:year>/<int:month>/<int:day>/',
        views.RequestDayArchiveView.as_view(month_format='%m'),
        name="archive_day"),
    ]

templates/about.html
{% extends 'base.html' %}
{% block content %}
  <div class="row equal">
    <div class="col-sm-4" style="background-color: red">
    </div>
    <div class="col-sm-8" style="background-color: blue">
      <img src="//placehold.it/200x150" class="img-responsive">
    </div>
    {% comment %}
    <div class="col-xs-12 col-sm-4" style="background-color: red">
      some content is here
    </div>
    <div class="col-xs-6 col-sm-4" style="background-color: yellow">
      <img src="//placehold.it/200x150" class="img-responsive">
    </div>
    <div class="col-xs-6 col-sm-4" style="background-color: blue">
      some more content
    </div>	
    {% endcomment %}
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cuzco</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    
    <link
       href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.15.min.css"
       rel="stylesheet" type="text/css">
    <link
       href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.15.min.css"
       rel="stylesheet" type="text/css">

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.15.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.15.min.js"></script>

    <script type="text/javascript"> Bokeh.set_log_level("info"); </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>

  <body>
    {% block bootstrap4_content %}
    <nav class="navbar navbar-expand-md bg-light navbar-light">
      <a class="nav-brand text-dark font-weight-bold" href="{% url 'main' %}">Cuzco</a>
      <ul class="navbar-nav">
	<li class="nav-item">
	  <a class="nav-link" href="{% url 'weather:cities' %}">Weatherama</a>
	</li>
	<li class="nav-item">
	  <a class="nav-link" href="{% url 'weather:archive' %}">Archive</a>
	</li>
	<li class="navbar-item">
	  <a class="nav-link" href="{% url 'about' %}">About</a>
	</li>
      </ul>
    </nav>
    <br>

    {% bootstrap_messages %}
    
    {% block content %}(no content){% endblock %}
    <br>
    <footer>
      <p>&copy; 2018 Company, Inc.
	{% block footer %}{% endblock %}
	<a href="http://us.rd.yahoo.com/dailynews/rss/weather/Country__Country/*https://weather.yahoo.com/country/state/city-2123268/" target="_blank">
	  <img src="https://poweredby.yahoo.com/purple.png" width="134" height="29"/></a>
      </p>
    </footer>
    {% endblock %}
  </body>
</html>

templates/main.html
{% extends 'base.html' %}

{% block content %}
<script src='http://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/d3.min.js'></script>
<div id='openweathermap-widget'></div>
<script type='text/javascript'>
  window.myWidgetParam = {
  id: 11,
  cityid: 498698,
  appid: '775670b8133c08911511535c6b1dfbdf',
  containerid: 'openweathermap-widget',
  };
  (function() {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.async = true;
  script.src = 'http://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(script, s);
  })();
</script>
{% endblock %}